### ISSUE TITLE
o2c-openobserve-collector-gateway-collector-0 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dockercore** [openobserve/openobserve-helm-chart#47]
环境：k8s 1.26.3
2024-03-05T02:34:46.701Z	info	service@v0.91.0/telemetry.go:86	Setting up own telemetry...
2024-03-05T02:34:46.702Z	info	service@v0.91.0/telemetry.go:203	Serving Prometheus metrics	{"address": ":8888", "level": "Basic"}
2024-03-05T02:34:46.702Z	info	kube/client.go:113	k8s filtering	{"kind": "processor", "name": "k8sattributes", "pipeline": "logs/k8s_events", "labelSelector": "", "fieldSelector": ""}
2024-03-05T02:34:46.703Z	info	kube/client.go:113	k8s filtering	{"kind": "processor", "name": "k8sattributes", "pipeline": "metrics", "labelSelector": "", "fieldSelector": ""}
2024-03-05T02:34:46.703Z	info	spanmetricsconnector@v0.91.0/connector.go:105	Building spanmetrics connector	{"kind": "connector", "name": "spanmetrics", "exporter_in_pipeline": "traces", "receiver_in_pipeline": "metrics"}
2024-03-05T02:34:46.704Z	info	kube/client.go:113	k8s filtering	{"kind": "processor", "name": "k8sattributes", "pipeline": "traces", "labelSelector": "", "fieldSelector": ""}
2024-03-05T02:34:46.705Z	info	service@v0.91.0/service.go:145	Starting otelcol-contrib...	{"Version": "0.91.0", "NumCPU": 8}
2024-03-05T02:34:46.705Z	info	extensions/extensions.go:34	Starting extensions...
2024-03-05T02:34:46.705Z	info	extensions/extensions.go:37	Extension is starting...	{"kind": "extension", "name": "zpages"}
2024-03-05T02:34:46.705Z	info	zpagesextension@v0.91.0/zpagesextension.go:53	Registered zPages span processor on tracer provider	{"kind": "extension", "name": "zpages"}
2024-03-05T02:34:46.705Z	info	zpagesextension@v0.91.0/zpagesextension.go:63	Registered Host's zPages	{"kind": "extension", "name": "zpages"}
2024-03-05T02:34:46.705Z	info	zpagesextension@v0.91.0/zpagesextension.go:75	Starting zPages extension	{"kind": "extension", "name": "zpages", "config": {"TCPAddr":{"Endpoint":"localhost:55679"}}}
2024-03-05T02:34:46.705Z	info	extensions/extensions.go:52	Extension started.	{"kind": "extension", "name": "zpages"}
2024-03-05T02:34:46.705Z	info	internal/resourcedetection.go:125	began detecting resource information	{"kind": "processor", "name": "resourcedetection", "pipeline": "logs/k8s_events"}
2024-03-05T02:34:46.705Z	info	internal/resourcedetection.go:139	detected resource information	{"kind": "processor", "name": "resourcedetection", "pipeline": "logs/k8s_events", "resource": {}}
2024-03-05T02:34:46.706Z	info	prometheusreceiver@v0.91.0/metrics_receiver.go:240	Starting discovery manager	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
2024-03-05T02:34:46.706Z	info	prometheusreceiver@v0.91.0/metrics_receiver.go:106	Starting target allocator discovery	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
2024-03-05T02:34:47.709Z	error	prometheusreceiver@v0.91.0/metrics_receiver.go:139	Failed to retrieve job list	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "error": "Get \"http://o2c-openobserve-collector-gateway-targetallocator:80/scrape_configs\": dial tcp 10.108.231.25:80: connect: connection refused"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).syncTargetAllocator
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.91.0/metrics_receiver.go:139
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).startTargetAllocator
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.91.0/metrics_receiver.go:108
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).Start
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.91.0/metrics_receiver.go:92
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll
	go.opentelemetry.io/collector/service@v0.91.0/internal/graph/graph.go:396
go.opentelemetry.io/collector/service.(*Service).Start
	go.opentelemetry.io/collector/service@v0.91.0/service.go:163
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents
	go.opentelemetry.io/collector/otelcol@v0.91.0/collector.go:190
go.opentelemetry.io/collector/otelcol.(*Collector).Run
	go.opentelemetry.io/collector/otelcol@v0.91.0/collector.go:229
go.opentelemetry.io/collector/otelcol.NewCommand.func1
	go.opentelemetry.io/collector/otelcol@v0.91.0/command.go:27
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.runInteractive
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:27
main.run
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:11
main.main
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:20
runtime.main
	runtime/proc.go:267
2024-03-05T02:34:47.709Z	info	service@v0.91.0/service.go:185	Starting shutdown...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45ed740]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver.(*k8seventsReceiver).Shutdown(0xc003254360, {0xc002eacb20, 0xc0039171b8})
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver@v0.91.0/receiver.go:82 +0x60
go.opentelemetry.io/collector/service/internal/graph.(*Graph).ShutdownAll(0xc002eb9680, {0x8d77e70, 0xdd0eec0})
	go.opentelemetry.io/collector/service@v0.91.0/internal/graph/graph.go:435 +0x1c8
go.opentelemetry.io/collector/service.(*Service).Shutdown(0xc002ecc3c0, {0x8d77e70, 0xdd0eec0})
	go.opentelemetry.io/collector/service@v0.91.0/service.go:191 +0xd7
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc0024f3900, {0x8d77e70, 0xdd0eec0})
	go.opentelemetry.io/collector/otelcol@v0.91.0/collector.go:191 +0x745
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc0024f3900, {0x8d77e70, 0xdd0eec0})
	go.opentelemetry.io/collector/otelcol@v0.91.0/collector.go:229 +0x52
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc00247e600, {0x7e783c5?, 0x7?, 0x7e70b8b?})
	go.opentelemetry.io/collector/otelcol@v0.91.0/command.go:27 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc00247e600, {0xc0000b40d0, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00247e600)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x81f88a8?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.runInteractive({0x81f88a8, {{0x7ea34eb, 0xf}, {0x7f38cd5, 0x1f}, {0x7e74c28, 0x6}}, 0x0, {0x0, 0x0}, ...})
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:27 +0x3d
main.run(...)
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:11
main.main()
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:20 +0x118

**Comment by prabhatsharma** [comment]
fixed by https://github.com/openobserve/openobserve-helm-chart/pull/49
